# Example GitHub Action to scan a Terraform config
# See https://github.com/mondoohq/actions/tree/main/terraform-hcl for additional usage information.

name: mondoo-cnspec-scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: where am I
        run: pwd && ls -la
      - name: Scan with cnspec
        uses: mondoohq/actions/terraform-hcl@main
        with:
          service-account-credentials: ${{ secrets.MONDOO_CONFIG_BASE64 }}
          path: "./"
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
      - name: TF init 
        run: terraform init 
      - id: plan
        run: terraform plan -no-color -out tf_plan
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
      - name: take a look
        run: pwd && ls -la

          